@extends('layouts.master')
@section('title')
    AF Logistics - Privacy Policy
@stop
@section('body')
    <link href="{{ URL::to('css/alt-css.css') }}" rel="stylesheet">
    @include('includes.header')
    <section data-stellar-background-ratio="0.5" style="background-image: url('{{ URL::to('images/custom2.jpg') }}');background-position: inherit;
        background-repeat: no-repeat;
        background-attachment: local;
        background-size: cover;
        min-height: 650px;">
        <div class="container">
            <div class="row">
                <div class="col-sm-8" style="background-color: #fff">
                    <h3 class="section-title">Privacy Policy.</h3>
                    <p>
                        This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
                        We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from http://aflogisticsandmining.com/
                    </p>
                    <p>
                    <h4 class="text-primary"><strong>Definitions</strong></h4>
                    <ul>
                        <li><strong>Service - </strong>Service is the http://aflogisticsandmining.com/ website operated by AF Logistics, Mining & Petroleum Company Limited.</li>
                        <li><strong>Personal Data - </strong>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
                        <li><strong>Usage Data - </strong>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                        <li><strong>Cookies - </strong>Cookies are small files stored on your device (computer or mobile device).</li>
                    </ul>
                    </p>
                    <p>
                    <h4 class="text-primary"><strong>Information Collection and Use</strong></h4>
                        We collect several different types of information for various purposes to provide and improve our Service to you.
                    </p>
                    <p>
                    <h6 class="text-primary"><strong>Types of Data Collected</strong></h6>
                    <h6 class="text-primary"><strong>Personal Data</strong></h6>
                    While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
                    <ul>
                        <li>Email address</li>
                        <li>First name and last name</li>
                        <li>Phone number</li>
                        <li>Address, State, Province, ZIP/Postal code, City</li>
                        <li>Cookies and Usage Data</li>
                    </ul>
                    <h6 class="text-primary"><strong>Data Usage</strong></h6>
                    We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                    <h6 class="text-primary"><strong>Tracking Cookies Data</strong></h6>
                    We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.<br>
                    Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.<br>
                    You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.<br>
                    Examples of Cookies we use:<br>
                    <ul>
                        <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
                        <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                        <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
                    </ul>
                    </p>
                    <p>
                    <h4 class="text-primary"><strong>Security of Data</strong></h4>
                        The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                    </p>
                    <p>
                    <h4 class="text-primary"><strong>Contact Us</strong></h4>
                    If you have any questions about these Privacy Policy, <a href="#footer" class="smoothScroll text-danger">please contact us.</a>
                    </p>
                    <ul class="wow fadeInUp social-icon" data-wow-delay="0.4s">
                        <li><a target="_blank" title="Facebook-aflogistics" href="https://facebook.com/102543527821470" class="fa fa-facebook-square" attr="facebook icon"></a></li>
                        <li><a target="_blank" title="Twitter-aflogistics" href="https://twitter.com/aflogistics_gh" class="fa fa-twitter"></a></li>
                        <li><a target="_blank" title="Instagram-aflogistics" href="https://instagram.com/aflogistics_gh" class="fa fa-instagram"></a></li>
                        <li><a target="_blank" title="Messenger-aflogistics" href="https://m.me/102543527821470" class="fa fa-comment"></a></li>
                    </ul>
                </div>
                <div class="col-sm-4"></div>
            </div>

        </div>
    </section>
    @include('includes.footer')
@stop
